export { watch } from './apiWatch'
export { queuePreFlushCbs } from './scheduler'
export { h } from './h'
export { createVNode, Fragment, Text, Comment } from './vnode'
export { createRenderer } from './renderer'
export type { CustomElement } from './renderer'
